title: Jonathan Peereman
logo: /assets/img/leaf.jpg
description: Researcher in forest ecology and remote sensing at the Water-Environment-Development Unit of Université de Liège (Belgium)
presentation: Conservation, forest ecology, remote sensing, tropical environments, disturbance ecology
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
